/*
 * This file is autogenerated by Meddela, any modification done to this file
 * will be lost when the code is regenerated.
 */
#ifndef CAN_NODE_BATTERY_CONF_H
#define CAN_NODE_BATTERY_CONF_H

#define NODE_ID 0x31U
#define NUMBER_OF_CAN_MESSAGE_CONFIGS 2U

/* Message masks */
#define CAN_MESSAGE_BATTERYCONTROL_MASK 0x500000U
#define CAN_MESSAGE_BATTERYCONTROL_INDEX 0U

#define CAN_MESSAGE_BATTERYSTATUS_MASK 0x600000U
#define CAN_MESSAGE_BATTERYSTATUS_INDEX 1U

#endif /* End of CAN_NODE_BATTERY_CONF_H */
