/*
 * This file is autogenerated by Meddela, any modification done to this file
 * will be lost when the code is regenerated.
 */
#include <DAVE.h>
#include "tasks.h"
#include "MessageManager.h"
#include "CAN_Config.h"
#include "CAN_Config_XMC1400.h"

#define MESSAGE_MANAGER_STACK_DEPTH	300U

#define MESSAGE_QUEUE_LENGTH		12U
#define MESSAGE_QUEUE_ITEM_SIZE		sizeof (Message_t)

QueueHandle_t xQueue_Messages;
TaskHandle_t xMessageManagerHandle = NULL;


void MessageManager_Send_BatteryStatus(BatteryStatus_t *s, uint32_t to_node)
{
	uint8_t data[8] = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U };

	data[0U] |= ((uint8_t) (s->Current >> 0U) << 0U) & 255U;
	data[1U] |= ((uint8_t) (s->Current >> 8U) << 0U) & 255U;
	
	data[2U] |= ((uint8_t) (s->BatteryOneVoltage >> 0U) << 0U) & 255U;
	data[3U] |= ((uint8_t) (s->BatteryOneVoltage >> 8U) << 0U) & 255U;
	
	data[4U] |= ((uint8_t) (s->BatteryTwoVoltage >> 0U) << 0U) & 255U;
	data[5U] |= ((uint8_t) (s->BatteryTwoVoltage >> 8U) << 0U) & 255U;
	
	data[6U] |= ((uint8_t) (s->BatteryThreeVoltage >> 0U) << 0U) & 255U;
	data[7U] |= ((uint8_t) (s->BatteryThreeVoltage >> 8U) << 0U) & 255U;
	
	CAN_NODE_0_SendMessage(CAN_MESSAGE_BATTERYSTATUS_INDEX, (uint8_t *) data);
}


void MessageManager_PushReceivedMessage(Message_t *message)
{
	BaseType_t xHigherPriorityTaskWoken;
	xHigherPriorityTaskWoken = pdFALSE;

	xQueueSendFromISR(xQueue_Messages, message, &xHigherPriorityTaskWoken);
}

void MessageManager_HandleReceivedMessage(Message_t message)
{
	uint8_t from_node_id = (message.id >> 4U) & 0xFFU;
	uint8_t to_node_id = (message.id >> 12U) & 0xFFU;

	if ((message.id & CAN_MESSAGE_BATTERYCONTROL_MASK) == CAN_MESSAGE_BATTERYCONTROL_MASK) {
		BatteryControl_t s;

		// Parse BatteryControl to struct

		s.Off = 0U;
		s.Off += ((message.data[0U]) & 255U);

		Handle_BatteryControl_Received(s, from_node_id, to_node_id);
	}
}

void MessageManager_Main(void *pvParameters)
{
	Message_t message;

	while (1U) {
		if (xQueueReceive(xQueue_Messages, &message, (TickType_t) 2000)) {
			// Route it
			MessageManager_HandleReceivedMessage(message);
		}
	}
}

void MessageManager_Init(void)
{
	xQueue_Messages = xQueueCreate(MESSAGE_QUEUE_LENGTH, MESSAGE_QUEUE_ITEM_SIZE);
	xTaskCreate(MessageManager_Main, "MessageManager_Main", MESSAGE_MANAGER_STACK_DEPTH, NULL, (tskIDLE_PRIORITY + 3), &xMessageManagerHandle);
}
